markets:
- includes:
  - Salar de Cauchari-Olaroz
  - Chaerhan
  - Salar de Centenario
  - East Taijinar
  - Lakkor Tso
  - Qinghai Yiliping
  - Salar de Atacama
  - Salar de Olaroz
  - Fenix
  - Silver Peak
  - Tres Quebradas
  - Zhabuye
  - Sal de los Angeles
  - Salar del Hombre Muerto North
  - Kachi
  - Maricunga
  - Salar de Pastos Grandes
  - Pozuelos
  - Sal de Vida
  - Salar de Arizaro
  - Salar de Tolillar
  - Salar del Rincon
  - Salar de Uyuni
  - Upper Rhine Graben
  name: market for lithium carbonate, from brine, S&P forecasts
  reference product: lithium carbonate, battery-grade
  replaces:
  - location: GLO
    name: lithium carbonate production, from concentrated brine
    product: lithium carbonate
  unit: kilogram
production pathways:
  Chaerhan:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Chaerhan
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Chaerhan Lake
  East Taijinar:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_East Taijinar
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|East Taijinair
  Fenix:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Fenix
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Salar del Hombre Muerto
  Kachi:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Kachi
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Kachi
  Lakkor Tso:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Lakkor Tso
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Lakkor Tso Salt Lake
  Maricunga:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Maricunga
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Maricunga
  Pozuelos:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Pozuelos
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|PPG
  Qinghai Yiliping:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Qinghai Yiliping
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Qinghai Yiliping
  Sal de Vida:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Sal de Vida
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Sal de Vida
  Sal de los Angeles:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Sal de los Angeles
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Sal de los Angeles
  Salar de Arizaro:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Salar de Arizaro
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Salar De Arizaro
  Salar de Atacama:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Salar de Atacama
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Salar de Atacama
  Salar de Cauchari-Olaroz:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Salar de Cauchari-Olaroz
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Cauchari-Olaroz
  Salar de Centenario:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Salar de Centenario
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Cuenca Centenario-Ratones
  Salar de Olaroz:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Salar de Olaroz
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Salar de Olaroz
  Salar de Pastos Grandes:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Salar de Pastos Grandes
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Pastos Grandes
  Salar de Tolillar:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Salar de Tolillar
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Salar de Tolillar
  Salar de Uyuni:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Salar de Uyuni
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Uyuni Salt Flat
  Salar del Hombre Muerto North:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Salar del Hombre Muerto North
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Hombre Muerto North
  Salar del Rincon:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Salar del Rincon
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Salar del Rincon
  Silver Peak:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Silver Peak
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Silver Peak
  Tres Quebradas:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Tres Quebradas
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Tres Quebradas
  Upper Rhine Graben:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Upper Rhine Graben
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Vulcan
  Zhabuye:
    ecoinvent alias:
      exists in original database: false
      name: df_rotary_dryer_Zhabuye
      new dataset: false
      reference product: df_rotary_dryer
      regionalize: false
    production volume:
      variable: Production|Lithium|Brine (Salar)|Zhabuye
